//! Emits the Liquid Glass palette as Kotlin, for the WebView Android app.
//!
//! `cargo run --example android_theme -p wat-theme -- <theme.toml> > Glass.kt`
//!
//! The WebView browser draws its interface with Android views rather than with
//! `wat-paint`, so it cannot share the renderer — but it can share the numbers.
//! Transcribing them by hand is how two apps that are meant to look identical
//! quietly stop matching, so they are generated from the same TOML the Rust
//! browser loads, and the generated file is committed so the Android build does
//! not need a Rust toolchain.

use std::path::PathBuf;

use wat_css::Color;
use wat_theme::Theme;

/// Android wants `0xAARRGGBB`; the themes are RGBA.
fn argb(color: Color) -> String {
    format!(
        "0x{:02X}{:02X}{:02X}{:02X}.toInt()",
        color.a, color.r, color.g, color.b
    )
}

fn main() {
    let path: PathBuf = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "crates/wat-theme/themes/liquid-glass.toml".into())
        .into();
    let theme = Theme::load(&path).unwrap_or_else(|error| {
        eprintln!("cannot read {}: {error}", path.display());
        std::process::exit(1);
    });

    for (object, dark) in [("Light", false), ("Dark", true)] {
        let resolved = theme.resolve(dark);
        if !dark {
            println!(
                "// Generated by `cargo run --example android_theme -p wat-theme`.\n\
                 // Source of truth: {}\n\
                 // Do not edit; edit the TOML and regenerate.\n\
                 package com.whatabrowser.wat.webview\n\n\
                 /** One palette, in Android's 0xAARRGGBB. */\n\
                 interface GlassPalette {{\n    \
                 val canvas: Int; val page: Int; val surface: Int; val surfaceRaised: Int\n    \
                 val text: Int; val textMuted: Int; val textOnAccent: Int\n    \
                 val accent: Int; val accentSoft: Int\n    \
                 val border: Int; val borderStrong: Int\n    \
                 val danger: Int; val success: Int; val warning: Int\n    \
                 /** The wash over a glass surface, already at its tint strength. */\n    \
                 val glassTint: Int\n    \
                 val glassEdge: Int\n    \
                 val glassRim: Int\n\
                 }}\n",
                path.display()
            );
            println!("/** Geometry is shared: it does not change with the colour scheme. */");
            println!("object GlassGeometry {{");
            println!(
                "    const val radiusSmall = {}f",
                resolved.geometry.radius_small
            );
            println!(
                "    const val radiusMedium = {}f",
                resolved.geometry.radius_medium
            );
            println!(
                "    const val radiusLarge = {}f",
                resolved.geometry.radius_large
            );
            println!(
                "    const val radiusPill = {}f",
                resolved.geometry.radius_pill
            );
            println!("    const val spacing = {}f", resolved.geometry.spacing);
            println!(
                "    const val borderWidth = {}f",
                resolved.geometry.border_width
            );
            println!(
                "    const val topBarHeight = {}f",
                resolved.geometry.mobile_top_height
            );
            println!(
                "    const val bottomBarHeight = {}f",
                resolved.geometry.mobile_bottom_height
            );
            println!("}}\n");
        }

        // The tint is applied at its strength here rather than at draw time, so
        // the view code has one colour to use and cannot forget the multiply.
        let tint = Color::rgba(
            resolved.glass.tint.r,
            resolved.glass.tint.g,
            resolved.glass.tint.b,
            (resolved.glass.tint.a as f32 * resolved.glass.tint_strength).round() as u8,
        );

        println!("object Glass{object} : GlassPalette {{");
        for (name, color) in [
            ("canvas", resolved.palette.canvas),
            ("page", resolved.palette.page),
            ("surface", resolved.palette.surface),
            ("surfaceRaised", resolved.palette.surface_raised),
            ("text", resolved.palette.text),
            ("textMuted", resolved.palette.text_muted),
            ("textOnAccent", resolved.palette.text_on_accent),
            ("accent", resolved.palette.accent),
            ("accentSoft", resolved.palette.accent_soft),
            ("border", resolved.palette.border),
            ("borderStrong", resolved.palette.border_strong),
            ("danger", resolved.palette.danger),
            ("success", resolved.palette.success),
            ("warning", resolved.palette.warning),
            ("glassTint", tint),
            ("glassEdge", resolved.glass.edge),
            ("glassRim", resolved.glass.rim_color),
        ] {
            println!("    override val {name} = {}", argb(color));
        }
        println!("}}\n");
    }
}
