//! The box tree: what layout produces and painting consumes.

use std::collections::HashMap;
use std::rc::Rc;

use crate::geom::{Point, Rect, Size2D};
use wat_dom::NodeId;
use wat_style::{ComputedStyle, FontStyle, Sides};
use wat_text::FontRequest;

/// Builds the font request implied by a computed style.
pub fn font_request(style: &ComputedStyle) -> FontRequest {
    FontRequest {
        families: style.font_family.clone(),
        weight: style.font_weight,
        italic: style.font_style != FontStyle::Normal,
        size: style.font_size,
        letter_spacing: style.letter_spacing,
        word_spacing: style.word_spacing,
    }
}

/// A run of text placed on a line.
#[derive(Clone, Debug, PartialEq)]
pub struct TextFragment {
    /// The text as it should be drawn, after white-space processing.
    pub text: String,
    /// Distance from the fragment's top edge down to the baseline.
    pub baseline: f32,
    /// Set when the run was stretched to justify a line.
    pub extra_word_spacing: f32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReplacedKind {
    Image,
    /// A replaced element we cannot render, drawn as a labelled placeholder.
    Unsupported,
}

/// A replaced element: an image, or a placeholder standing in for one.
#[derive(Clone, Debug, PartialEq)]
pub struct Replaced {
    pub kind: ReplacedKind,
    /// Resolved absolute URL, when there is one.
    pub url: Option<String>,
    /// `alt` text, or the tag name for unsupported content.
    pub label: String,
    /// Intrinsic size in pixels, if known.
    pub intrinsic: Option<Size2D>,
}

/// What a box is.
#[derive(Clone, Debug, PartialEq)]
pub enum BoxKind {
    /// A block container in normal flow.
    Block,
    /// An atomic inline that lays out as a block internally.
    InlineBlock,
    Flex,
    Grid,
    /// A line box generated by inline layout.
    Line,
    /// A run of text on a line.
    Text(TextFragment),
    Replaced(Replaced),
    /// The part of an inline element that falls on one line. Carries the
    /// element's background, border and text decoration.
    InlineFragment,
    /// A list item marker such as a bullet or a number.
    Marker(String),
    /// A block-level box that only exists to hold inline content, generated
    /// when a block container mixes block and inline children.
    AnonymousBlock,
}

impl BoxKind {
    pub fn is_text(&self) -> bool {
        matches!(self, BoxKind::Text(_))
    }

    /// Does the box participate in inline layout as an atomic item?
    pub fn is_atomic_inline(&self) -> bool {
        matches!(self, BoxKind::InlineBlock | BoxKind::Replaced(_))
    }

    pub fn is_block_level(&self) -> bool {
        matches!(
            self,
            BoxKind::Block | BoxKind::Flex | BoxKind::Grid | BoxKind::AnonymousBlock
        )
    }
}

/// One box in the tree, positioned in absolute document coordinates.
#[derive(Clone, Debug)]
pub struct LayoutBox {
    /// The DOM node that generated the box, if any.
    pub node: Option<NodeId>,
    pub style: Rc<ComputedStyle>,
    pub kind: BoxKind,
    pub parent: Option<usize>,
    pub children: Vec<usize>,

    /// Border box, in absolute document coordinates.
    pub rect: Rect,
    pub margin: Sides<f32>,
    pub border: Sides<f32>,
    pub padding: Sides<f32>,
    /// Distance from `rect.y` to the box's baseline.
    pub baseline: f32,
    /// Extent of the content, which may exceed the box when it scrolls.
    pub scrollable: Size2D,
    /// How far this box's content is scrolled. Layout leaves it at zero; the
    /// engine sets it, and painting shifts descendants by it.
    pub scroll_offset: Point,
    /// Set on boxes whose `position` takes them out of flow.
    pub out_of_flow: bool,
}

impl LayoutBox {
    pub fn new(node: Option<NodeId>, style: Rc<ComputedStyle>, kind: BoxKind) -> Self {
        LayoutBox {
            node,
            style,
            kind,
            parent: None,
            children: Vec::new(),
            rect: Rect::ZERO,
            margin: Sides::ZERO,
            border: Sides::ZERO,
            padding: Sides::ZERO,
            baseline: 0.0,
            scrollable: Size2D::ZERO,
            scroll_offset: Point::ZERO,
            out_of_flow: false,
        }
    }

    /// Border + padding on each edge.
    pub fn edges(&self) -> Sides<f32> {
        Sides {
            top: self.border.top + self.padding.top,
            right: self.border.right + self.padding.right,
            bottom: self.border.bottom + self.padding.bottom,
            left: self.border.left + self.padding.left,
        }
    }

    /// The padding box: inside the border, outside the padding edge.
    pub fn padding_box(&self) -> Rect {
        self.rect.inset(self.border)
    }

    /// The content box.
    pub fn content_box(&self) -> Rect {
        self.rect.inset(self.edges())
    }

    /// The margin box.
    pub fn margin_box(&self) -> Rect {
        self.rect.outset(self.margin)
    }

    /// Can this box scroll, and does it have anything to scroll?
    pub fn scrolls_vertically(&self) -> bool {
        self.style.overflow_y.scrollable()
            && self.scrollable.height > self.content_box().height + 0.5
    }

    /// Maximum vertical scroll offset.
    pub fn max_scroll_y(&self) -> f32 {
        (self.scrollable.height - self.content_box().height).max(0.0)
    }
}

/// One entry in an inline formatting context.
#[derive(Clone, Debug)]
pub enum InlineItem {
    Text {
        node: NodeId,
        style: Rc<ComputedStyle>,
        text: String,
    },
    /// An inline-level box that lays out as a unit: inline-block or replaced.
    Atomic(usize),
    /// Start of an inline element's content.
    Open {
        node: Option<NodeId>,
        style: Rc<ComputedStyle>,
    },
    /// End of the most recently opened inline element.
    Close,
    /// A forced line break, from `<br>`.
    Break,
}

/// The result of laying out a document.
#[derive(Clone, Debug, Default)]
pub struct LayoutTree {
    pub boxes: Vec<LayoutBox>,
    pub root: Option<usize>,
    /// Viewport the tree was laid out for.
    pub viewport: Size2D,
    /// Total size of the document, which may exceed the viewport.
    pub document_size: Size2D,
    /// Inline content owned by each block container that has any. Inline layout
    /// turns these into `Line` children.
    pub inline_items: HashMap<usize, Vec<InlineItem>>,
}

impl LayoutTree {
    pub fn new(viewport: Size2D) -> Self {
        LayoutTree {
            boxes: Vec::new(),
            root: None,
            viewport,
            document_size: Size2D::ZERO,
            inline_items: HashMap::new(),
        }
    }

    /// Does `index` establish an inline formatting context?
    pub fn has_inline_content(&self, index: usize) -> bool {
        self.inline_items.get(&index).is_some_and(|i| !i.is_empty())
    }

    pub fn push(&mut self, layout_box: LayoutBox) -> usize {
        let index = self.boxes.len();
        self.boxes.push(layout_box);
        index
    }

    pub fn add_child(&mut self, parent: usize, child: usize) {
        self.boxes[parent].children.push(child);
        self.boxes[child].parent = Some(parent);
    }

    pub fn get(&self, index: usize) -> &LayoutBox {
        &self.boxes[index]
    }

    pub fn get_mut(&mut self, index: usize) -> &mut LayoutBox {
        &mut self.boxes[index]
    }

    pub fn len(&self) -> usize {
        self.boxes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.boxes.is_empty()
    }

    pub fn children(&self, index: usize) -> &[usize] {
        &self.boxes[index].children
    }

    /// Depth-first pre-order indices, parents before children.
    pub fn preorder(&self) -> Vec<usize> {
        let mut out = Vec::with_capacity(self.boxes.len());
        if let Some(root) = self.root {
            let mut stack = vec![root];
            while let Some(index) = stack.pop() {
                out.push(index);
                for child in self.boxes[index].children.iter().rev() {
                    stack.push(*child);
                }
            }
        }
        out
    }

    /// The first box generated by `node`.
    pub fn box_for_node(&self, node: NodeId) -> Option<usize> {
        self.boxes.iter().position(|b| b.node == Some(node))
    }

    /// The innermost box containing `point`, ignoring boxes that cannot be hit.
    pub fn hit_test(&self, point: Point) -> Option<usize> {
        let mut best = None;
        for index in self.preorder() {
            let layout_box = &self.boxes[index];
            if layout_box.style.visibility == wat_style::Visibility::Hidden {
                continue;
            }
            // Text fragments are hit through their inline ancestors, which carry
            // the interesting node (a link, say).
            if layout_box.rect.contains(point) {
                best = Some(index);
            }
        }
        best
    }

    /// Walks up from `index` to find the nearest box whose node is an element
    /// matching `predicate`.
    pub fn ancestor_matching(
        &self,
        index: usize,
        mut predicate: impl FnMut(&LayoutBox) -> bool,
    ) -> Option<usize> {
        let mut current = Some(index);
        while let Some(i) = current {
            if predicate(&self.boxes[i]) {
                return Some(i);
            }
            current = self.boxes[i].parent;
        }
        None
    }

    /// Union of every box rectangle, used to size the scrollable document.
    pub fn bounds(&self) -> Rect {
        self.boxes
            .iter()
            .fold(Rect::ZERO, |acc, b| acc.union(&b.rect))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use wat_style::LengthPercentage;

    fn style() -> Rc<ComputedStyle> {
        Rc::new(ComputedStyle::initial())
    }

    #[test]
    fn box_geometry_derives_from_edges() {
        let mut layout_box = LayoutBox::new(None, style(), BoxKind::Block);
        layout_box.rect = Rect::new(0.0, 0.0, 100.0, 100.0);
        layout_box.border = Sides::all(2.0);
        layout_box.padding = Sides::all(8.0);

        assert_eq!(layout_box.padding_box(), Rect::new(2.0, 2.0, 96.0, 96.0));
        assert_eq!(layout_box.content_box(), Rect::new(10.0, 10.0, 80.0, 80.0));
        assert_eq!(layout_box.edges().horizontal(), 20.0);
    }

    #[test]
    fn tree_links_parents_and_children() {
        let mut tree = LayoutTree::new(Size2D::new(800.0, 600.0));
        let root = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.root = Some(root);
        let child = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.add_child(root, child);

        assert_eq!(tree.children(root), &[child]);
        assert_eq!(tree.get(child).parent, Some(root));
        assert_eq!(tree.preorder(), vec![root, child]);
    }

    #[test]
    fn preorder_visits_children_left_to_right() {
        let mut tree = LayoutTree::new(Size2D::ZERO);
        let root = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.root = Some(root);
        let a = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        let b = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.add_child(root, a);
        tree.add_child(root, b);
        let a_child = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.add_child(a, a_child);

        assert_eq!(tree.preorder(), vec![root, a, a_child, b]);
    }

    #[test]
    fn hit_test_prefers_the_innermost_later_box() {
        let mut tree = LayoutTree::new(Size2D::new(200.0, 200.0));
        let root = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.root = Some(root);
        tree.get_mut(root).rect = Rect::new(0.0, 0.0, 200.0, 200.0);
        let child = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.add_child(root, child);
        tree.get_mut(child).rect = Rect::new(50.0, 50.0, 50.0, 50.0);

        assert_eq!(tree.hit_test(Point::new(60.0, 60.0)), Some(child));
        assert_eq!(tree.hit_test(Point::new(10.0, 10.0)), Some(root));
        assert_eq!(tree.hit_test(Point::new(500.0, 500.0)), None);
    }

    #[test]
    fn hidden_boxes_are_not_hit() {
        let mut tree = LayoutTree::new(Size2D::new(200.0, 200.0));
        let root = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.root = Some(root);
        tree.get_mut(root).rect = Rect::new(0.0, 0.0, 200.0, 200.0);

        let mut hidden_style = ComputedStyle::initial();
        hidden_style.visibility = wat_style::Visibility::Hidden;
        let hidden = tree.push(LayoutBox::new(None, Rc::new(hidden_style), BoxKind::Block));
        tree.add_child(root, hidden);
        tree.get_mut(hidden).rect = Rect::new(0.0, 0.0, 100.0, 100.0);

        assert_eq!(tree.hit_test(Point::new(10.0, 10.0)), Some(root));
    }

    #[test]
    fn scroll_extent_needs_overflow_and_room() {
        let mut style = ComputedStyle::initial();
        style.overflow_y = wat_style::Overflow::Auto;
        let mut layout_box = LayoutBox::new(None, Rc::new(style), BoxKind::Block);
        layout_box.rect = Rect::new(0.0, 0.0, 100.0, 100.0);
        layout_box.scrollable = Size2D::new(100.0, 250.0);

        assert!(layout_box.scrolls_vertically());
        assert_eq!(layout_box.max_scroll_y(), 150.0);

        layout_box.scrollable = Size2D::new(100.0, 50.0);
        assert!(!layout_box.scrolls_vertically());
        assert_eq!(layout_box.max_scroll_y(), 0.0);
    }

    #[test]
    fn font_request_mirrors_the_style() {
        let mut style = ComputedStyle::initial();
        style.font_family = vec!["Inter".into()];
        style.font_size = 22.0;
        style.font_weight = 600;
        style.font_style = FontStyle::Italic;
        style.letter_spacing = 1.5;

        let request = font_request(&style);
        assert_eq!(request.families, vec!["Inter"]);
        assert_eq!(request.size, 22.0);
        assert_eq!(request.weight, 600);
        assert!(request.italic);
        assert_eq!(request.letter_spacing, 1.5);
    }

    #[test]
    fn bounds_covers_every_box() {
        let mut tree = LayoutTree::new(Size2D::ZERO);
        let root = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.root = Some(root);
        tree.get_mut(root).rect = Rect::new(0.0, 0.0, 10.0, 10.0);
        let child = tree.push(LayoutBox::new(None, style(), BoxKind::Block));
        tree.add_child(root, child);
        tree.get_mut(child).rect = Rect::new(0.0, 0.0, 40.0, 300.0);

        let bounds = tree.bounds();
        assert_eq!(bounds.width, 40.0);
        assert_eq!(bounds.height, 300.0);
    }

    #[test]
    fn radius_values_survive_on_the_style() {
        let mut style = ComputedStyle::initial();
        style.border_radius = wat_style::Corners::all(LengthPercentage::Px(12.0));
        let layout_box = LayoutBox::new(None, Rc::new(style), BoxKind::Block);
        assert_eq!(
            layout_box.style.border_radius.top_left,
            LengthPercentage::Px(12.0)
        );
    }
}
