// Generated by `cargo run --example android_theme -p wat-theme`.
// Source of truth: crates/wat-theme/themes/liquid-glass.toml
// Do not edit; edit the TOML and regenerate.
package com.whatabrowser.wat.webview

/** One palette, in Android's 0xAARRGGBB. */
interface GlassPalette {
    val canvas: Int; val page: Int; val surface: Int; val surfaceRaised: Int
    val text: Int; val textMuted: Int; val textOnAccent: Int
    val accent: Int; val accentSoft: Int
    val border: Int; val borderStrong: Int
    val danger: Int; val success: Int; val warning: Int
    /** The wash over a glass surface, already at its tint strength. */
    val glassTint: Int
    val glassEdge: Int
    val glassRim: Int
}

/** Geometry is shared: it does not change with the colour scheme. */
object GlassGeometry {
    const val radiusSmall = 8f
    const val radiusMedium = 14f
    const val radiusLarge = 22f
    const val radiusPill = 999f
    const val spacing = 8f
    const val borderWidth = 1f
    const val topBarHeight = 56f
    const val bottomBarHeight = 64f
}

object GlassLight : GlassPalette {
    override val canvas = 0xFFE8EDF5.toInt()
    override val page = 0xFFFFFFFF.toInt()
    override val surface = 0xD9FFFFFF.toInt()
    override val surfaceRaised = 0xF2FFFFFF.toInt()
    override val text = 0xFF10141C.toInt()
    override val textMuted = 0x9910141C.toInt()
    override val textOnAccent = 0xFFFFFFFF.toInt()
    override val accent = 0xFF0A84FF.toInt()
    override val accentSoft = 0x240A84FF.toInt()
    override val border = 0x1F10141C.toInt()
    override val borderStrong = 0x3810141C.toInt()
    override val danger = 0xFFFF3B30.toInt()
    override val success = 0xFF30B05C.toInt()
    override val warning = 0xFFFF9F0A.toInt()
    override val glassTint = 0x6BFFFFFF.toInt()
    override val glassEdge = 0x59FFFFFF.toInt()
    override val glassRim = 0xFFFFFFFF.toInt()
}

object GlassDark : GlassPalette {
    override val canvas = 0xFF0B0E14.toInt()
    override val page = 0xFF141820.toInt()
    override val surface = 0xCC2A303D.toInt()
    override val surfaceRaised = 0xE6353C4B.toInt()
    override val text = 0xFFF2F5FA.toInt()
    override val textMuted = 0x8CF2F5FA.toInt()
    override val textOnAccent = 0xFFFFFFFF.toInt()
    override val accent = 0xFF4CA6FF.toInt()
    override val accentSoft = 0x334CA6FF.toInt()
    override val border = 0x1AFFFFFF.toInt()
    override val borderStrong = 0x33FFFFFF.toInt()
    override val danger = 0xFFFF6B60.toInt()
    override val success = 0xFF4CD07D.toInt()
    override val warning = 0xFFFFB83D.toInt()
    override val glassTint = 0x801C222E.toInt()
    override val glassEdge = 0x2EFFFFFF.toInt()
    override val glassRim = 0xFFFFFFFF.toInt()
}

